client_max_body_size 10M;
client_max_body_size 10M;

server {
    listen 80;
    server_name _;
    root /home/site/wwwroot/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        # Pastikan path socket ini benar untuk Azure PHP 8.2
        fastcgi_pass unix:/var/run/php/php-fpm.sock; 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}